#!/usr/bin/env python3
"""SubX nest SEO stubs: write /<slug>.html for every site.json nest so GitHub Pages
answers /<slug> with 200 (extensionless .html) instead of the 404.html bounce.
The stub carries nest title/blurb/canonical, then hands off to the shell exactly like
404.html (sessionStorage subx.restorePath -> location.replace('/')). Stubs never copy
index.html, so they cannot drift from the shell. Re-run after editing site.json nests.

Catalog nests live in site.json. Rooms a member adds with '+' are stored on their
user document (userNests) and are not known here; those URLs still open through
404.html. Do not invent stubs for them.

Usage: python3 nest_stubs.py <repo_dir> [domain]
"""
import json, os, re, sys, html
MARK = '<!-- subx-nest-stub: generated by nest_stubs.py; edit site.json, not this file -->'
RESERVED = {'index','404','home','explore','following','notifications','chat','profile','news','about',
            'terms','privacy','api','admin','watchlist','stories','feed','thoughts','hot','new','factory',
            'gate','site','taxonomy','styles','favicon','robots','og','cname'}
SLUG_RE = re.compile(r'^[a-z0-9]+(?:-[a-z0-9]+)*$')

def main(repo, domain=None):
    site = json.load(open(os.path.join(repo, 'site.json')))
    if not domain:
        try: domain = open(os.path.join(repo, 'CNAME')).read().strip()
        except Exception: domain = ''
    idx = open(os.path.join(repo, 'index.html')).read() if os.path.exists(os.path.join(repo,'index.html')) else ''
    m = re.search(r'<meta\s+name="robots"\s+content="([^"]+)"', idx, re.I)
    robots = m.group(1) if m else 'noindex, nofollow'
    name = site.get('name') or site.get('siteId') or domain
    wrote, skipped = [], []
    want = set()
    for n in site.get('nests') or []:
        slug = str(n.get('slug') or '').strip().lower()
        if not SLUG_RE.match(slug) or slug in RESERVED:
            skipped.append((slug, 'reserved/invalid')); continue
        path = os.path.join(repo, slug + '.html')
        if os.path.exists(path) and MARK not in open(path).read():
            skipped.append((slug, 'file exists (not a stub)')); continue
        want.add(slug + '.html')
        label = n.get('label') or slug
        blurb = n.get('blurb') or ''
        canon = f'https://{domain}/{slug}' if domain else f'/{slug}'
        e = html.escape
        doc = f'''<!DOCTYPE html>
{MARK}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="robots" content="{e(robots)}">
  <title>{e(label)} · {e(name)}</title>
  <meta name="description" content="{e(blurb)}">
  <link rel="canonical" href="{e(canon)}">
  <meta property="og:title" content="{e(label)} · {e(name)}">
  <meta property="og:description" content="{e(blurb)}">
  <meta property="og:url" content="{e(canon)}">
  <script>
    (function () {{
      var path = location.pathname || '/{slug}';
      if (path.charAt(0) !== '/') path = '/' + path;
      path = path.replace(/\\.html$/, '');
      try {{ sessionStorage.setItem('subx.restorePath', path + (location.search || '') + (location.hash || '')); }} catch (e) {{}}
      location.replace('/' + (location.search || '') + (location.hash || ''));
    }})();
  </script>
</head>
<body>
  <main>
    <h1>{e(label)}</h1>
    <p>{e(blurb)}</p>
    <p><a href="/">Open {e(name)}</a></p>
  </main>
</body>
</html>
'''
        open(path, 'w').write(doc)
        wrote.append(slug)
    # remove stale stubs for nests that no longer exist
    removed = []
    for f in os.listdir(repo):
        if f.endswith('.html') and f not in want:
            p = os.path.join(repo, f)
            try:
                if MARK in open(p).read():
                    os.remove(p); removed.append(f)
            except Exception: pass
    print(json.dumps({'repo': repo, 'wrote': wrote, 'skipped': skipped, 'removed': removed}))

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
